// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Varyag.Models;

#nullable disable

namespace Varyag.Migrations
{
    [DbContext(typeof(VaryagContext))]
    [Migration("20250308190920_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Varyag.Models.AnythingElse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPath1")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPath2")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery")
                        .HasColumnType("longtext");

                    b.Property<string>("Route")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AnythingElse");
                });

            modelBuilder.Entity("Varyag.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArticleName")
                        .HasColumnType("longtext");

                    b.Property<string>("ArticleRoute")
                        .HasColumnType("longtext");

                    b.Property<string>("ArticleType")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleFotoPreview")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleImgScale")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleImgX")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleImgY")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleStory")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery1")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery10")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery11")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery12")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery13")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery14")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery15")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery2")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery3")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery4")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery5")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery6")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery7")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery8")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery9")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortFotoPreview")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortImgScale")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortImgX")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortImgY")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortStory")
                        .HasColumnType("longtext");

                    b.Property<string>("Text1")
                        .HasColumnType("longtext");

                    b.Property<string>("Text10")
                        .HasColumnType("longtext");

                    b.Property<string>("Text11")
                        .HasColumnType("longtext");

                    b.Property<string>("Text12")
                        .HasColumnType("longtext");

                    b.Property<string>("Text13")
                        .HasColumnType("longtext");

                    b.Property<string>("Text14")
                        .HasColumnType("longtext");

                    b.Property<string>("Text15")
                        .HasColumnType("longtext");

                    b.Property<string>("Text2")
                        .HasColumnType("longtext");

                    b.Property<string>("Text3")
                        .HasColumnType("longtext");

                    b.Property<string>("Text4")
                        .HasColumnType("longtext");

                    b.Property<string>("Text5")
                        .HasColumnType("longtext");

                    b.Property<string>("Text6")
                        .HasColumnType("longtext");

                    b.Property<string>("Text7")
                        .HasColumnType("longtext");

                    b.Property<string>("Text8")
                        .HasColumnType("longtext");

                    b.Property<string>("Text9")
                        .HasColumnType("longtext");

                    b.Property<string>("WideFotoPreview")
                        .HasColumnType("longtext");

                    b.Property<string>("WideImgScale")
                        .HasColumnType("longtext");

                    b.Property<string>("WideImgX")
                        .HasColumnType("longtext");

                    b.Property<string>("WideImgY")
                        .HasColumnType("longtext");

                    b.Property<string>("WideStory")
                        .HasColumnType("longtext");

                    b.HasKey("ArticleId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Varyag.Models.Foto", b =>
                {
                    b.Property<int>("FotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alt")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("NewsID")
                        .HasColumnType("int");

                    b.Property<byte[]>("ProjectFoto")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("ShipProjectID")
                        .HasColumnType("int");

                    b.HasKey("FotoID");

                    b.HasIndex("NewsID");

                    b.HasIndex("ShipProjectID");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("Varyag.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasColumnType("longtext");

                    b.Property<int>("KeyWord")
                        .HasColumnType("int");

                    b.Property<string>("LinkedProjectNames")
                        .HasColumnType("longtext");

                    b.Property<string>("MainStory")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleFotoPreview")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleImgScale")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleImgX")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleImgY")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleStory")
                        .HasColumnType("longtext");

                    b.Property<string>("NewsDate")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToGallery")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToVideo1")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToVideo2")
                        .HasColumnType("longtext");

                    b.Property<string>("PathToVideo3")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortFotoPreview")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortImgScale")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortImgX")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortImgY")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortStory")
                        .HasColumnType("longtext");

                    b.Property<string>("WideFotoPreview")
                        .HasColumnType("longtext");

                    b.Property<string>("WideImgScale")
                        .HasColumnType("longtext");

                    b.Property<string>("WideImgX")
                        .HasColumnType("longtext");

                    b.Property<string>("WideImgY")
                        .HasColumnType("longtext");

                    b.Property<string>("WideStory")
                        .HasColumnType("longtext");

                    b.HasKey("NewsId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Varyag.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("BoatRow")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BoatSail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BoatTraditional")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BoatYal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Botik")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Deep")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EnginePower")
                        .HasColumnType("longtext");

                    b.Property<string>("FreshWaterCap")
                        .HasColumnType("longtext");

                    b.Property<string>("FuelCap")
                        .HasColumnType("longtext");

                    b.Property<bool>("KaterCabin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KaterFish")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KaterPass")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KaterProject")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KaterRow")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LadyaProject")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LadyaRow")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LadyaSail")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Length")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("MainFoto")
                        .HasColumnType("longblob");

                    b.Property<bool>("MaketCinema")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MaketDesign")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MaketMuseum")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MaketStudy")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mass")
                        .HasColumnType("longtext");

                    b.Property<bool>("Motosailer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NumberOfOars")
                        .HasColumnType("longtext");

                    b.Property<string>("PassengerCap")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<string>("Route")
                        .HasColumnType("longtext");

                    b.Property<string>("SailArea")
                        .HasColumnType("longtext");

                    b.Property<bool>("SailboatHistorical")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SailboatProject")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SailboatStudy")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("ShipSheme")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("ShipShemeFull")
                        .HasColumnType("longblob");

                    b.Property<bool>("Shvertbot")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SleepingAreas")
                        .HasColumnType("longtext");

                    b.Property<string>("Speed")
                        .HasColumnType("longtext");

                    b.Property<string>("Volume")
                        .HasColumnType("longtext");

                    b.Property<string>("Windth")
                        .HasColumnType("longtext");

                    b.Property<bool>("Yacht")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ProjectID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Varyag.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Varyag.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Varyag.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varyag.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Varyag.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Varyag.Models.Foto", b =>
                {
                    b.HasOne("Varyag.Models.News", "News")
                        .WithMany()
                        .HasForeignKey("NewsID");

                    b.HasOne("Varyag.Models.Project", "ShipProject")
                        .WithMany("ShipFotos")
                        .HasForeignKey("ShipProjectID");

                    b.Navigation("News");

                    b.Navigation("ShipProject");
                });

            modelBuilder.Entity("Varyag.Models.Project", b =>
                {
                    b.Navigation("ShipFotos");
                });
#pragma warning restore 612, 618
        }
    }
}
